apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas
spec:
  selector:
    matchLabels:
      run: saas
  replicas: 1
  template:
    metadata:
      name: saas
      labels:
        run: saas 
    spec:
      nodeSelector:
        kubernetes.io/hostname: "minikube"
      containers: 
      - name: saas
        image: sverreydt/saas-app
        ports: 
        - containerPort: 5000
      
